// Code generated by hertz generator.

package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path"
	"simplest_script/core"
	"simplest_script/core/conf"
	"simplest_script/crontab"
	"simplest_script/exec"
	"simplest_script/internal/script"
	"time"

	"github.com/cloudwego/hertz/pkg/common/hlog"
	hertzlogrus "github.com/hertz-contrib/logger/logrus"
	"gopkg.in/natefinch/lumberjack.v2"
)

var configFile *string
var c conf.Config

func main() {
	mode := flag.String("mode", "cron", "run mode: cron or queue")
	env := os.Getenv("SCRIPT_ENV")

	switch env {
	case core.EnvRelease:
		configFile = flag.String("f", "./etc/release.yaml", "the config file")
	case core.EnvTest:
		configFile = flag.String("f", "/data/etc/test.yaml", "the config file")
	case core.EnvDev:
		configFile = flag.String("f", "./etc/dev.yaml", "the config file")
	default:
		configFile = flag.String("f", "./etc/dev.yaml", "the config file")
	}

	flag.Parse()

	conf.MustLoad(*configFile, &c)

	if err := os.MkdirAll(c.Logger.Path, 0o777); err != nil {
		log.Println(err.Error())
		return
	}

	// 将文件名设置为日期
	logFileName := time.Now().Format("20060102") + ".log"
	fileName := path.Join(c.Logger.Path, logFileName)
	if _, err := os.Stat(fileName); err != nil {
		if _, err := os.Create(fileName); err != nil {
			log.Println(err.Error())
			return
		}
	}

	logger := hertzlogrus.NewLogger()
	// 提供压缩和删除
	lumberjackLogger := &lumberjack.Logger{
		Filename:   fileName,
		MaxSize:    c.Logger.MaxSize,    // 一个文件最大可达 单位M。
		MaxBackups: c.Logger.MaxBackups, // 最多同时保存文件数。
		MaxAge:     c.Logger.MaxAge,     // 一个文件最多可以保存天数。
		Compress:   c.Logger.Compress,   // 是否 gzip 压缩。
	}

	logger.SetOutput(lumberjackLogger)
	logger.SetLevel(hlog.LevelDebug)

	hlog.SetLogger(logger)

	if *mode == "queue" {
		// 注册定时任务
		InitCrontab()

		// 注册异步消费
		exec.Init()

		select {}
	} else {
		hlog.Info(fmt.Sprintf("脚本args %v", os.Args))

		if len(os.Args) > 1 {
			uk := os.Args[1]
			args := os.Args[2:]
			res := script.Exec(args...)

			crontab.UpdateCrontabLog(uk, "success", res)
		}

	}
}
